FROM nginx:1.28.0@sha256:0ad9e58f00f6a0d92f8c0a2a32285366a0ee948d9f91aee4a2c965a5516c59d5

ARG VCS_REF="missing"
ARG BUILD_DATE="missing"

ENV VCS_REF=${VCS_REF}
ENV BUILD_DATE=${BUILD_DATE}

LABEL org.label-schema.vcs-ref=${VCS_REF} \
    org.label-schema.build-date=${BUILD_DATE}

ADD nginx.conf /etc/nginx/nginx.conf

RUN mkdir /app
COPY index.html /app
COPY assets /app

EXPOSE 8080:8080

CMD ["nginx", "-g", "daemon off;"]
