name: Filer CI

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      working_directory:
        type: string
        default: "."
      codecov_flag:
          type: string

jobs:
  linting:

  testing:

  verify-build: